config/routes.rb
Financeflow2::Application.routes.draw do

  put 'timer/:id' => 'customers#timer_set', :as => 'timer_set'
  get 'financenext/:id' => 'customers#finance', :as => 'financenext'
  get 'finance/:id' => 'customers#currentstep', :as => 'finance'
  put 'details/:id' => 'customers#detail', :as => 'details'
  get 'step1/new/:id' => 'stepones#show', :as => 'step1show'
  get 'step1/:id' => 'stepones#new', :as => 'step1'
  get 'step1/edit/:id' => 'stepones#edit', :as => 'step1edit'
  get 'step2/new/:id' => 'steptwos#show', :as => 'step2show'
  get 'step2/:id' => 'steptwos#new', :as => 'step2'
  get 'step2/edit/:id' => 'steptwos#edit', :as => 'step2edit'
  get 'step3/new/:id' => 'stepthrees#show', :as => 'step3show'
  get 'step3/:id' => 'stepthrees#new', :as => 'step3'
  get 'step3/edit/:id' => 'stepthrees#edit', :as => 'step3edit'
  get 'step4/new/:id' => 'stepfours#show', :as => 'step4show'
  get 'step4/:id' => 'stepfours#new', :as => 'step4'
  get 'step4/edit/:id' => 'stepfours#edit', :as => 'step4edit'
  get 'step5/new/:id' => 'stepfives#show', :as => 'step5show'
  get 'step5/:id' => 'stepfives#new', :as => 'step5'
  get 'step5/edit/:id' => 'stepfives#edit', :as => 'step5edit'
  get 'step6/new/:id' => 'stepsixes#show', :as => 'step6show'
  get 'step6/:id' => 'stepsixes#new', :as => 'step6'
  get 'step6/edit/:id' => 'stepsixes#edit', :as => 'step6edit'
  get 'step7/new/:id' => 'stepsevens#show', :as => 'step7show'
  get 'step7/:id' => 'stepsevens#new', :as => 'step7'
  get 'step7/edit/:id' => 'stepsevens#edit', :as => 'step7edit'
  get 'step8/new/:id' => 'stepeights#show', :as => 'step8show'
  get 'step8/:id' => 'stepeights#new', :as => 'step8'
  get 'step8/edit/:id' => 'stepeights#edit', :as => 'step8edit'
  get 'step9/new/:id' => 'stepnines#show', :as => 'step9show'
  get 'step9/:id' => 'stepnines#new', :as => 'step9'
  get 'step9/edit/:id' => 'stepnines#edit', :as => 'step9edit'
  get 'step10/new/:id' => 'steptens#show', :as => 'step10show'
  get 'step10/:id' => 'steptens#new', :as => 'step10'
  get 'step10/edit/:id' => 'steptens#edit', :as => 'step10edit'
  get 'step11/new/:id' => 'stepelevens#show', :as => 'step11show'
  get 'step11/:id' => 'stepelevens#new', :as => 'step11'
  get 'step11/edit/:id' => 'stepelevens#edit', :as => 'step11edit'
  get 'step12/new/:id' => 'steptwelves#show', :as => 'step12show'
  get 'step12/:id' => 'steptwelves#new', :as => 'step12'
  get 'step12/edit/:id' => 'steptwelves#edit', :as => 'step12edit'
  get 'step13/new/:id' => 'stepthirteens#show', :as => 'step13show'
  get 'step13/:id' => 'stepthirteens#new', :as => 'step13'
  get 'step13/edit/:id' => 'stepthirteens#edit', :as => 'step13edit'
  get 'step14/new/:id' => 'stepfourteens#show', :as => 'step14show'
  get 'step14/:id' => 'stepfourteens#new', :as => 'step14'
  get 'step14/edit/:id' => 'stepfourteens#edit', :as => 'step14edit'
  get 'step15/new/:id' => 'stepfifteens#show', :as => 'step15show'
  get 'step15/:id' => 'stepfifteens#new', :as => 'step15'
  get 'step15/edit/:id' => 'stepfifteens#edit', :as => 'step15edit'
  resources :steptens
  resources :stepnines
  resources :stepeights
  resources :stepsevens
  resources :stepsixes
  resources :stepfives
  resources :stepfours
  resources :stepthrees
  resources :steptwos
  resources :stepones
  resources :stepfifteens
  resources :tickets
  resources :stepfourteens
  resources :stepthirteens
  resources :steptwelves
  resources :stepelevens
  devise_for :users#,  :controllers => { :registrations => "users/registrations" }
  match "/customers/add_new_comment" => "customers#add_new_comment", :as => "add_new_comment_to_customers", :via => [:post]
  get "remote/new"
  get "remote/back"
  get "remote/forward"
  get "remote/home"
  resources :customers do
    get :currentstep, :on => :member
    resources :comments
  end
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  root :to => "customers#index"
end

app/models/steptwo.rb
class Steptwo < ActiveRecord::Base
    belongs_to :customer
    def self.search(search)
    if search
      where('customer_lname LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/steptwos_controller.rb
class SteptwosController < ApplicationController
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction
  # GET /steptwos
  # GET /steptwos.xml
  def index
    @steptwos = Steptwo.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @steptwos }
    end
  end

  # GET /steptwos/1
  # GET /steptwos/1.xml
  def show
    @steptwo = Steptwo.find_by_customer_id(params[:id])
    @customer = Customer.find(params[:id])
    if Comment.find_by_commentable_id_and_title(params[:id],"Approved")
      @comments = Comment.find_all_by_commentable_id_and_title(params[:id],"Approved")
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @steptwo }
    end
  end

  # GET /steptwos/new
  # GET /steptwos/new.xml
  def new
    @steptwo = Steptwo.new
    @customer = Customer.find_by_id(params[:id])
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @steptwo }
    end
  end

  # GET /steptwos/1/edit
  def edit
    @steptwo = Steptwo.find_by_customer_id(params[:id])
    @customer = Customer.find_by_id(params[:id])
  end

  # POST /steptwos
  # POST /steptwos.xml
  def create
    @steptwo = Steptwo.new(params[:steptwo])

    respond_to do |format|
      if @steptwo.save
        format.html { redirect_to(root_path, :notice => 'Steptwo was successfully created.') }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @steptwo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /steptwos/1
  # PUT /steptwos/1.xml
  def update
    @steptwo = Steptwo.find(params[:id])

    respond_to do |format|
      if @steptwo.update_attributes(params[:steptwo])
        format.html { redirect_to(root_path, :notice => 'Steptwo was successfully updated.') }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @steptwo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /steptwos/1
  # DELETE /steptwos/1.xml
  def destroy
    @steptwo = Steptwo.find(params[:id])
    @steptwo.destroy

    respond_to do |format|
      format.html { redirect_to(steptwos_url) }
      format.xml  { head :ok }
    end
  end
  private
  def sort_column
    Customer.column_names.include?(params[:sort]) ? params[:sort] : "updated_at"
  end


  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end


end

app/helpers/steptwos_helper.rb
module SteptwosHelper
end

app/views/steptwos/_form.html.erb
<p>For Customer: <%= @customer.fname%> <%= @customer.lname%></p>
<% form_for(@steptwo) do |f|%>
    <% if @steptwo.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@steptwo.errors.count, "error") %> prohibited this customer from being saved:</h2>
          <ul>
            <% @steptwo.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= f.hidden_field :customer_id, :value => @customer.id%>
    <%= f.hidden_field :customer_fname, :value => @customer.fname%>
    <%= f.hidden_field :customer_lname, :value => @customer.lname%>
    <div class="wrapper">
      <div class="steponeform">
        <table style="margin-left: auto;margin-right: auto;text-align: left;">
          <tr>
            <td><%= f.label :complete, "Check this box when this step can be successfully marked Complete."%></td>
            <td><%= f.check_box :complete%></td>
          </tr>
          <tr><%= f.submit "Save Stage Two"%></tr>
        </table>
      </div>
    </div>
<% end %>

app/views/steptwos/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @steptwo %> |
<%= link_to 'Back', root_path %>

app/views/steptwos/index.html.erb
<div id="searchcontent">
<h2 id="searchtitle">Initial Conditions Received</h2>
<%= form_tag steptwos_path, :method => 'get' do%>
    <%= hidden_field_tag :direction, params[:direction]%>
    <%= hidden_field_tag :sort, params[:sort]%>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>
<table class="search">
  <tr>
    <th><span><%= sortable "customer_id", "Customer #"%>&nbsp;</span></th>
    <th><span><%= sortable "customer_lname", "Last" %>, <%= sortable "customer_fname", "First" %>&nbsp;</span></th>
    <th><span><%= sortable "title", "Step Status" %>&nbsp;</span></th>
    <th><span><%= sortable "updated_at", "Updated at" %>&nbsp;</span></th>
    <th>Modify</th>
    <th>Remove Step</th>
  </tr>
<tbody>
<% @steptwos.each do |steptwo| %>
  <tr>
    <td><%= steptwo.customer_id %></td>
    <td><%= steptwo.customer_lname.capitalize %>, <%= steptwo.customer_fname.capitalize %></td>
    <td><%= steptwo.title %></td>
    <td><%= steptwo.updated_at %></td>
    <td><%= link_to 'Edit', edit_steptwo_path(steptwo) %></td>
    <td><%= link_to 'Destroy', steptwo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</tbody>
</table>
<%= will_paginate @steptwos %>

<br />
</div>

app/views/steptwos/new.html.erb
<h1>2. Approved</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/steptwos/show.html.erb
<table style="margin-left: auto;margin-right: auto;text-align: left;"><tr>
  <td>
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @steptwo.customer_id %>
</p>

<p>
  <b>Customer fname:</b>
  <%= @steptwo.customer_fname %>
</p>

<p>
  <b>Customer lname:</b>
  <%= @steptwo.customer_lname %>
</p>

<p>
  <b>Complete:</b>
  <%= @steptwo.complete %>
</p></td>
<td>


<p>Update Customer Status</p>
    <% form_tag details_path(@customer.id), :method => 'put' do%>
        <%= text_field_tag "details"%>
        <%= submit_tag "Save", :name => nil%>
    <% end %>
    <!-- Comments Box -->
    <%= form_tag "/customers/add_new_comment" do %>
        <%= hidden_field_tag "id", @customer.id %>
        <%= hidden_field_tag "comment[commentable_id]", @customer.id %>
        <%= hidden_field_tag "comment[title]", "Approved" %>
        <%= hidden_field_tag "comment[user_id]", current_user.id %>
        <%= text_area_tag "comment[comment]" %><br>
        <%= submit_tag "Post Comment" %>
    <% end %><br>
<% if @comments%>
    <% @comments.each do |comment|   %>
        <%= comment.title %><br>
        <%= comment.comment %><br>
        <%= User.find(comment.user_id).email %><br><br>
    <%end%>
<% end %>
    </td>
</tr></table>
<%= link_to 'Edit', step2edit_path(params[:id])%> |
<%= link_to 'Back', root_path %>