config/routes.rb
Financeflow2::Application.routes.draw do

  put 'timer/:id' => 'customers#timer_set', :as => 'timer_set'
  get 'financenext/:id' => 'customers#finance', :as => 'financenext'
  get 'finance/:id' => 'customers#currentstep', :as => 'finance'
  put 'details/:id' => 'customers#detail', :as => 'details'
  get 'step1/new/:id' => 'stepones#show', :as => 'step1show'
  get 'step1/:id' => 'stepones#new', :as => 'step1'
  get 'step1/edit/:id' => 'stepones#edit', :as => 'step1edit'
  get 'step2/new/:id' => 'steptwos#show', :as => 'step2show'
  get 'step2/:id' => 'steptwos#new', :as => 'step2'
  get 'step2/edit/:id' => 'steptwos#edit', :as => 'step2edit'
  get 'step3/new/:id' => 'stepthrees#show', :as => 'step3show'
  get 'step3/:id' => 'stepthrees#new', :as => 'step3'
  get 'step3/edit/:id' => 'stepthrees#edit', :as => 'step3edit'
  get 'step4/new/:id' => 'stepfours#show', :as => 'step4show'
  get 'step4/:id' => 'stepfours#new', :as => 'step4'
  get 'step4/edit/:id' => 'stepfours#edit', :as => 'step4edit'
  get 'step5/new/:id' => 'stepfives#show', :as => 'step5show'
  get 'step5/:id' => 'stepfives#new', :as => 'step5'
  get 'step5/edit/:id' => 'stepfives#edit', :as => 'step5edit'
  get 'step6/new/:id' => 'stepsixes#show', :as => 'step6show'
  get 'step6/:id' => 'stepsixes#new', :as => 'step6'
  get 'step6/edit/:id' => 'stepsixes#edit', :as => 'step6edit'
  get 'step7/new/:id' => 'stepsevens#show', :as => 'step7show'
  get 'step7/:id' => 'stepsevens#new', :as => 'step7'
  get 'step7/edit/:id' => 'stepsevens#edit', :as => 'step7edit'
  get 'step8/new/:id' => 'stepeights#show', :as => 'step8show'
  get 'step8/:id' => 'stepeights#new', :as => 'step8'
  get 'step8/edit/:id' => 'stepeights#edit', :as => 'step8edit'
  get 'step9/new/:id' => 'stepnines#show', :as => 'step9show'
  get 'step9/:id' => 'stepnines#new', :as => 'step9'
  get 'step9/edit/:id' => 'stepnines#edit', :as => 'step9edit'
  get 'step10/new/:id' => 'steptens#show', :as => 'step10show'
  get 'step10/:id' => 'steptens#new', :as => 'step10'
  get 'step10/edit/:id' => 'steptens#edit', :as => 'step10edit'
  get 'step11/new/:id' => 'stepelevens#show', :as => 'step11show'
  get 'step11/:id' => 'stepelevens#new', :as => 'step11'
  get 'step11/edit/:id' => 'stepelevens#edit', :as => 'step11edit'
  get 'step12/new/:id' => 'steptwelves#show', :as => 'step12show'
  get 'step12/:id' => 'steptwelves#new', :as => 'step12'
  get 'step12/edit/:id' => 'steptwelves#edit', :as => 'step12edit'
  get 'step13/new/:id' => 'stepthirteens#show', :as => 'step13show'
  get 'step13/:id' => 'stepthirteens#new', :as => 'step13'
  get 'step13/edit/:id' => 'stepthirteens#edit', :as => 'step13edit'
  get 'step14/new/:id' => 'stepfourteens#show', :as => 'step14show'
  get 'step14/:id' => 'stepfourteens#new', :as => 'step14'
  get 'step14/edit/:id' => 'stepfourteens#edit', :as => 'step14edit'
  get 'step15/new/:id' => 'stepfifteens#show', :as => 'step15show'
  get 'step15/:id' => 'stepfifteens#new', :as => 'step15'
  get 'step15/edit/:id' => 'stepfifteens#edit', :as => 'step15edit'
  resources :steptens
  resources :stepnines
  resources :stepeights
  resources :stepsevens
  resources :stepsixes
  resources :stepfives
  resources :stepfours
  resources :stepthrees
  resources :steptwos
  resources :stepones
  resources :stepfifteens
  resources :tickets
  resources :stepfourteens
  resources :stepthirteens
  resources :steptwelves
  resources :stepelevens
  devise_for :users#,  :controllers => { :registrations => "users/registrations" }
  match "/customers/add_new_comment" => "customers#add_new_comment", :as => "add_new_comment_to_customers", :via => [:post]
  get "remote/new"
  get "remote/back"
  get "remote/forward"
  get "remote/home"
  resources :customers do
    get :currentstep, :on => :member
    resources :comments
  end
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  root :to => "customers#index"
end

app/models/stepfourteen.rb
class Stepfourteen < ActiveRecord::Base
  belongs_to :customer
    def self.search(search)
    if search
      where('customer_lname LIKE ?', "%#{search}%")
    else
      scoped
    end
    end
end

app/controllers/stepfourteens_controller.rb
class StepfourteensController < ApplicationController
  # GET /stepfourteens
  # GET /stepfourteens.xml
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction
  def index
    @stepfourteens = Stepfourteen.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stepfourteens }
    end
  end

  # GET /stepfourteens/1
  # GET /stepfourteens/1.xml
  def show
    @stepfourteen = Stepfourteen.find_by_customer_id(params[:id])
    @customer = Customer.find(params[:id])
    if Comment.find_by_commentable_id_and_title(params[:id],"Schedule Close")
      @comments = Comment.find_all_by_commentable_id_and_title(params[:id],"Schedule Close")
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @stepfourteen }
    end
  end

  # GET /stepfourteens/new
  # GET /stepfourteens/new.xml
  def new
    @stepfourteen = Stepfourteen.new
    @customer = Customer.find_by_id(params[:id])
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @stepfourteen }

    end
  end

  # GET /stepfourteens/1/edit
  def edit
    @stepfourteen = Stepfourteen.find_by_customer_id(params[:id])
    @customer = Customer.find_by_id(params[:id])
  end

  # POST /stepfourteens
  # POST /stepfourteens.xml
  def create
    @stepfourteen = Stepfourteen.new(params[:stepfourteen])

    respond_to do |format|
      if @stepfourteen.save
        format.html { redirect_to(root_path, :notice => 'Stepfourteen was successfully created.') }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @stepfourteen.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stepfourteens/1
  # PUT /stepfourteens/1.xml
  def update
    @stepfourteen = Stepfourteen.find(params[:id])

    respond_to do |format|
      if @stepfourteen.update_attributes(params[:stepfourteen])
        format.html { redirect_to(@stepfourteen, :notice => 'Stepfourteen was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @stepfourteen.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stepfourteens/1
  # DELETE /stepfourteens/1.xml
  def destroy
    @stepfourteen = Stepfourteen.find(params[:id])
    @stepfourteen.destroy

    respond_to do |format|
      format.html { redirect_to(stepfourteens_url) }
      format.xml  { head :ok }
    end
  end
  private
  def sort_column
    Customer.column_names.include?(params[:sort]) ? params[:sort] : "updated_at"
  end


  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/helpers/stepfourteens_helper.rb
module StepfourteensHelper
end

app/views/stepfourteens/_form.html.erb
<%= simple_form_for(@stepfourteen) do |f| %>
  <%= f.error_notification %>
  <h2>14. Schedule Close</h2>


  <p>Complete this step when the customer's loan has been finalized and is ready to be funded and closed. </p>
  <div class="inputs">
    <%= f.input :customer_id,    :as => :hidden, :input_html => {:value => @customer.id}     %>
    <%= f.input :customer_fname, :as => :hidden, :input_html => {:value => @customer.fname}  %>
    <%= f.input :customer_lname, :as => :hidden, :input_html => {:value => @customer.lname}  %>
    <%= f.input :updated_by, :as => :hidden, :input_html => {:value => current_user.email}   %>
    <%= f.input :complete %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stepfourteens/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @stepfourteen %> |
<%= link_to 'Back', stepfourteens_path %>

app/views/stepfourteens/index.html.erb
<h1>Listing stepfourteens</h1>

<table>
  <tr>
    <th>Customer</th>
    <th>Customer fname</th>
    <th>Customer lname</th>
    <th>Updated by</th>
    <th>Complete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stepfourteens.each do |stepfourteen| %>
  <tr>
    <td><%= stepfourteen.customer_id %></td>
    <td><%= stepfourteen.customer_fname %></td>
    <td><%= stepfourteen.customer_lname %></td>
    <td><%= stepfourteen.updated_by %></td>
    <td><%= stepfourteen.complete %></td>
    <td><%= link_to 'Show', stepfourteen %></td>
    <td><%= link_to 'Edit', edit_stepfourteen_path(stepfourteen) %></td>
    <td><%= link_to 'Destroy', stepfourteen, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stepfourteen', new_stepfourteen_path %>

app/views/stepfourteens/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', stepfourteens_path %>

app/views/stepfourteens/show.html.erb
<table style="margin-left: auto;margin-right: auto;text-align: left;"><tr>
  <td>
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @stepfourteen.customer_id %>
</p>

<p>
  <b>Customer fname:</b>
  <%= @stepfourteen.customer_fname %>
</p>

<p>
  <b>Customer lname:</b>
  <%= @stepfourteen.customer_lname %>
</p>

<p>
  <b>Complete:</b>
  <%= @stepfourteen.complete %>
</p></td>
<td>


<p>Update Customer Status</p>
    <% form_tag details_path(@customer.id), :method => 'put' do%>
        <%= text_field_tag "details"%>
        <%= submit_tag "Save", :name => nil%>
    <% end %>
    <!-- Comments Box -->
    <%= form_tag "/customers/add_new_comment" do %>
        <%= hidden_field_tag "id", @customer.id %>
        <%= hidden_field_tag "comment[commentable_id]", @customer.id %>
        <%= hidden_field_tag "comment[title]", "Schedule Close" %>
        <%= hidden_field_tag "comment[user_id]", current_user.id %>
        <%= text_area_tag "comment[comment]" %><br>
        <%= submit_tag "Post Comment" %>
    <% end %><br>
<% if @comments%>
    <% @comments.each do |comment|   %>
        <%= comment.title %><br>
        <%= comment.comment %><br>
        <%= User.find(comment.user_id).email %><br><br>
    <%end%>
<% end %>
    </td>
</tr></table>
<%= link_to 'Edit', step14edit_path(params[:id])%> |
<%= link_to 'Back', root_path %>