config/routes.rb
Financeflow2::Application.routes.draw do

  put 'timer/:id' => 'customers#timer_set', :as => 'timer_set'
  get 'financenext/:id' => 'customers#finance', :as => 'financenext'
  get 'finance/:id' => 'customers#currentstep', :as => 'finance'
  put 'details/:id' => 'customers#detail', :as => 'details'
  get 'step1/new/:id' => 'stepones#show', :as => 'step1show'
  get 'step1/:id' => 'stepones#new', :as => 'step1'
  get 'step1/edit/:id' => 'stepones#edit', :as => 'step1edit'
  get 'step2/new/:id' => 'steptwos#show', :as => 'step2show'
  get 'step2/:id' => 'steptwos#new', :as => 'step2'
  get 'step2/edit/:id' => 'steptwos#edit', :as => 'step2edit'
  get 'step3/new/:id' => 'stepthrees#show', :as => 'step3show'
  get 'step3/:id' => 'stepthrees#new', :as => 'step3'
  get 'step3/edit/:id' => 'stepthrees#edit', :as => 'step3edit'
  get 'step4/new/:id' => 'stepfours#show', :as => 'step4show'
  get 'step4/:id' => 'stepfours#new', :as => 'step4'
  get 'step4/edit/:id' => 'stepfours#edit', :as => 'step4edit'
  get 'step5/new/:id' => 'stepfives#show', :as => 'step5show'
  get 'step5/:id' => 'stepfives#new', :as => 'step5'
  get 'step5/edit/:id' => 'stepfives#edit', :as => 'step5edit'
  get 'step6/new/:id' => 'stepsixes#show', :as => 'step6show'
  get 'step6/:id' => 'stepsixes#new', :as => 'step6'
  get 'step6/edit/:id' => 'stepsixes#edit', :as => 'step6edit'
  get 'step7/new/:id' => 'stepsevens#show', :as => 'step7show'
  get 'step7/:id' => 'stepsevens#new', :as => 'step7'
  get 'step7/edit/:id' => 'stepsevens#edit', :as => 'step7edit'
  get 'step8/new/:id' => 'stepeights#show', :as => 'step8show'
  get 'step8/:id' => 'stepeights#new', :as => 'step8'
  get 'step8/edit/:id' => 'stepeights#edit', :as => 'step8edit'
  get 'step9/new/:id' => 'stepnines#show', :as => 'step9show'
  get 'step9/:id' => 'stepnines#new', :as => 'step9'
  get 'step9/edit/:id' => 'stepnines#edit', :as => 'step9edit'
  get 'step10/new/:id' => 'steptens#show', :as => 'step10show'
  get 'step10/:id' => 'steptens#new', :as => 'step10'
  get 'step10/edit/:id' => 'steptens#edit', :as => 'step10edit'
  get 'step11/new/:id' => 'stepelevens#show', :as => 'step11show'
  get 'step11/:id' => 'stepelevens#new', :as => 'step11'
  get 'step11/edit/:id' => 'stepelevens#edit', :as => 'step11edit'
  get 'step12/new/:id' => 'steptwelves#show', :as => 'step12show'
  get 'step12/:id' => 'steptwelves#new', :as => 'step12'
  get 'step12/edit/:id' => 'steptwelves#edit', :as => 'step12edit'
  get 'step13/new/:id' => 'stepthirteens#show', :as => 'step13show'
  get 'step13/:id' => 'stepthirteens#new', :as => 'step13'
  get 'step13/edit/:id' => 'stepthirteens#edit', :as => 'step13edit'
  get 'step14/new/:id' => 'stepfourteens#show', :as => 'step14show'
  get 'step14/:id' => 'stepfourteens#new', :as => 'step14'
  get 'step14/edit/:id' => 'stepfourteens#edit', :as => 'step14edit'
  get 'step15/new/:id' => 'stepfifteens#show', :as => 'step15show'
  get 'step15/:id' => 'stepfifteens#new', :as => 'step15'
  get 'step15/edit/:id' => 'stepfifteens#edit', :as => 'step15edit'
  resources :steptens
  resources :stepnines
  resources :stepeights
  resources :stepsevens
  resources :stepsixes
  resources :stepfives
  resources :stepfours
  resources :stepthrees
  resources :steptwos
  resources :stepones
  resources :stepfifteens
  resources :tickets
  resources :stepfourteens
  resources :stepthirteens
  resources :steptwelves
  resources :stepelevens
  devise_for :users#,  :controllers => { :registrations => "users/registrations" }
  match "/customers/add_new_comment" => "customers#add_new_comment", :as => "add_new_comment_to_customers", :via => [:post]
  get "remote/new"
  get "remote/back"
  get "remote/forward"
  get "remote/home"
  resources :customers do
    get :currentstep, :on => :member
    resources :comments
  end
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  root :to => "customers#index"
end

app/models/stepthree.rb
class Stepthree < ActiveRecord::Base
    belongs_to :customer
    def self.search(search)
    if search
      where('customer_lname LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/stepthrees_controller.rb
class StepthreesController < ApplicationController
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction
  # GET /stepthrees
  # GET /stepthrees.xml
  def index
    @stepthrees = Stepthree.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stepthrees }
    end
  end

  # GET /stepthrees/1
  # GET /stepthrees/1.xml
  def show
    @stepthree = Stepthree.find_by_customer_id(params[:id])
    @customer = Customer.find(params[:id])
    if Comment.find_by_commentable_id_and_title(params[:id],"GFE Received")
      @comments = Comment.find_all_by_commentable_id_and_title(params[:id],"GFE Received")
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @stepthree }
    end
  end

  # GET /stepthrees/new
  # GET /stepthrees/new.xml
  def new
    @stepthree = Stepthree.new
    @customer = Customer.find_by_id(params[:id])
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @stepthree }
    end
  end

  # GET /stepthrees/1/edit
  def edit
    @stepthree = Stepthree.find_by_customer_id(params[:id])
    @customer = Customer.find_by_id(@stepone.customer_id)
  end

  # POST /stepthrees
  # POST /stepthrees.xml
  def create
    @stepthree = Stepthree.new(params[:stepthree])

    respond_to do |format|
      if @stepthree.save
        format.html { redirect_to(root_path, :notice => 'Stepthree was successfully created.') }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @stepthree.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stepthrees/1
  # PUT /stepthrees/1.xml
  def update
    @stepthree = Stepthree.find(params[:id])

    respond_to do |format|
      if @stepthree.update_attributes(params[:stepthree])
        format.html { redirect_to(root_path, :notice => 'Stepthree was successfully updated.') }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @stepthree.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stepthrees/1
  # DELETE /stepthrees/1.xml
  def destroy
    @stepthree = Stepthree.find(params[:id])
    @stepthree.destroy

    respond_to do |format|
      format.html { redirect_to(stepthrees_url) }
      format.xml  { head :ok }
    end
  end
  private
  def sort_column
    Customer.column_names.include?(params[:sort]) ? params[:sort] : "updated_at"
  end


  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end


end

app/helpers/stepthrees_helper.rb
module StepthreesHelper
end

app/views/stepthrees/_form.html.erb
<%= simple_form_for(@stepthree) do |f| %>
  <%= f.error_notification %>
  <h2>3. GFE Received</h2>

  <p>If this step is incomplete, click the button below without checking the box. Once the box has been checked, this step will be complete. </p>

  <div class="inputs">
    <%= f.input :customer_id,    :as => :hidden, :input_html => {:value => @customer.id}     %>
    <%= f.input :customer_fname, :as => :hidden, :input_html => {:value => @customer.fname}  %>
    <%= f.input :customer_lname, :as => :hidden, :input_html => {:value => @customer.lname}  %>
    <%= f.input :complete %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stepthrees/edit.html.erb
<h1>Editing stepthree</h1>

<%= render 'form' %>

<%= link_to 'Show', @stepthree %> |
<%= link_to 'Back', stepthrees_path %>

app/views/stepthrees/index.html.erb
<div id="searchcontent">
<h2 id="searchtitle">Submitted for Preapproval</h2>
<%= form_tag stepthrees_path, :method => 'get' do%>
    <%= hidden_field_tag :direction, params[:direction]%>
    <%= hidden_field_tag :sort, params[:sort]%>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>
<table class="search">
  <tr>
    <th><span><%= sortable "customer_id", "Customer #"%>&nbsp;</span></th>
    <th><span><%= sortable "customer_lname", "Last" %>, <%= sortable "customer_fname", "First" %>&nbsp;</span></th>
    <th><span><%= sortable "title", "Step Status" %>&nbsp;</span></th>
    <th><span><%= sortable "updated_at", "Updated at" %>&nbsp;</span></th>
    <th>Modify</th>
    <th>Remove Step</th>
  </tr>
<tbody>
<% @stepthrees.each do |stepthree| %>
  <tr>
    <td><%= stepthree.customer_id %></td>
    <td><%= stepthree.customer_lname.capitalize %>, <%= stepthree.customer_fname.capitalize %></td>
    <td><%= stepthree.title %></td>
    <td><%= stepthree.updated_at %></td>
    <td><%= link_to 'Edit', edit_stepthree_path(stepthree) %></td>
    <td><%= link_to 'Destroy', stepthree, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</tbody>
</table>
<%= will_paginate @stepthrees %>

<br />
</div>

app/views/stepthrees/show.html.erb
<table style="margin-left: auto;margin-right: auto;text-align: left;"><tr>
  <td>
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @stepthree.customer_id %>
</p>

<p>
  <b>Customer fname:</b>
  <%= @stepthree.customer_fname %>
</p>

<p>
  <b>Customer lname:</b>
  <%= @stepthree.customer_lname %>
</p>

<p>
  <b>Complete:</b>
  <%= @stepthree.complete %>
</p></td>
<td>


<p>Update Customer Status</p>
    <% form_tag details_path(@customer.id), :method => 'put' do%>
        <%= text_field_tag "details"%>
        <%= submit_tag "Save", :name => nil%>
    <% end %>
    <!-- Comments Box -->
    <%= form_tag "/customers/add_new_comment" do %>
        <%= hidden_field_tag "id", @customer.id %>
        <%= hidden_field_tag "comment[commentable_id]", @customer.id %>
        <%= hidden_field_tag "comment[title]", "GFE Received" %>
        <%= hidden_field_tag "comment[user_id]", current_user.id %>
        <%= text_area_tag "comment[comment]" %><br>
        <%= submit_tag "Post Comment" %>
    <% end %><br>
<% if @comments%>
    <% @comments.each do |comment|   %>
        <%= comment.title %><br>
        <%= comment.comment %><br>
        <%= User.find(comment.user_id).email %><br><br>
    <%end%>
<% end %>
    </td>
</tr></table>
<%= link_to 'Edit', step3edit_path(params[:id])%> |
<%= link_to 'Back', root_path %>